### ISSUE TITLE
Input Textのラベルを非表示にできるようにしたい

### ISSUE THREAD

**Issue by matsuritech** [matsuritech/matsuri-ui#235]
<img width="280" alt="スクリーンショット 2019-08-12 15 40 01" src="https://user-images.githubusercontent.com/49267254/62848722-bfb94b80-bd17-11e9-97c4-967f83ae529b.png">
添付画像のように、ラベルがからの場合でも高さを取ってしまうケースがあり、空の場合は非表示が望ましいと思われますが、いかがですか？

**Comment by hrdtbs** [comment]
これはバグですね。

**Comment by hrdtbs** [comment]
@tawashichan @matsuritech v4.6.5 修正しました。
