### ISSUE TITLE
Buttonの文字色について

### ISSUE THREAD

**Issue by tawashichan** [matsuritech/matsuri-ui#237]
<img width="253" alt="スクリーンショット 2019-08-12 16 27 55" src="https://user-images.githubusercontent.com/31276400/62850591-4c670800-bd1e-11e9-99e6-d89a2cf954b7.png">
<img width="229" alt="スクリーンショット 2019-08-12 16 28 06" src="https://user-images.githubusercontent.com/31276400/62850592-4c670800-bd1e-11e9-9042-ed068ba4d1bd.png">
<img width="237" alt="スクリーンショット 2019-08-12 16 28 11" src="https://user-images.githubusercontent.com/31276400/62850593-4c670800-bd1e-11e9-9720-36a9ff14ffda.png">
colorをgrayにしてButtonコンポーネントを使用したところ、文字色がデザインと異なっているように思われましたので報告します。
使用するにあたってのコードは下記のようになります

```
  <Button color={"gray"}>
    キャンセル
  </Button>
```

**Comment by hrdtbs** [comment]
filledの未指定とstyle.cssの--palette-gray-textによるものv4.6.6で対応済み
